### ISSUE TITLE
Missing GLIBC_2.29

### ISSUE THREAD

**Issue by fw-nytra** [dmstr/docker-fonts#6]
When running Step 8/15, I get the following error: 
```
Step 8/15 : RUN cd /google-fonts     && find . -name '*.ttf' -print0 | xargs -P $(nproc --all) --null -n 1 webify --no-svg
 ---> Running in 2ef15cb6a13e
webify: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by webify)
The command '/bin/sh -c cd /google-fonts     && find . -name '*.ttf' -print0 | xargs -P $(nproc --all) --null -n 1 webify --no-svg' returned a non-zero code: 123
```
Do you got any idea why ?

**Comment by handcode** [comment]
I can not reproduce this.

Seems like you don't have the expected base image when building and therefore the libc version doesn't fit (maybe an older nginx image?) Have you pulled the nginx before build?

Which debian and libc version do you have in your nginx image?
`docker run --rm nginx cat /etc/debian_version`
`docker run --rm nginx ldd --version`

Anyway, I have explicitly set the builder image in the dockerfile to debian:bullseye (versions fit) and introduced a docker build ARG TEST_BUILD for testing so that we can debug such problems faster/easier (39533214e6eaaa3dd3c799d4fcfef021be375998).

Please test: https://github.com/dmstr/docker-fonts/tree/dev/test-build#test-build

**Comment by fw-nytra** [comment]
My debian version is 10.10 
And my libc version is ldd (Debian GLIBC 2.28-10) 2.28 
Anyway, running the TEST_BUILD worked like a charme. 
Setting the builder image to specifc version debian:bullseye has brought the solution.
Thank you very much!
